"""
Django settings for movie_backend project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

# Suppress the pkg_resources deprecation warning from djangorestframework-simplejwt
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning, module="pkg_resources")

from pathlib import Path
from decouple import config
from datetime import timedelta
import os

# ENABLE Redis for production-grade caching
USE_REDIS_CACHE = True  # Set to True since Redis is installed

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', default=True, cast=bool)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')

# Application definition
DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = [
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'drf_spectacular',
]

LOCAL_APPS = [
    'accounts',
    'movies',
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'movie_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'movie_backend.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# ==========================================
# REST FRAMEWORK CONFIGURATION
# ==========================================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# ==========================================
# JWT CONFIGURATION
# ==========================================
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# ==========================================
# CORS CONFIGURATION
# ==========================================
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Only in development

# ==========================================
# REDIS CACHE CONFIGURATION
# ==========================================
if USE_REDIS_CACHE:
    try:
        # Test Redis connection first
        import redis
        r = redis.Redis(host='127.0.0.1', port=6379, db=1, socket_connect_timeout=1)
        r.ping()
        
        # Redis is available, use full configuration
        CACHES = {
            'default': {
                'BACKEND': 'django_redis.cache.RedisCache',
                'LOCATION': config('REDIS_URL', default='redis://127.0.0.1:6379/1'),
                'OPTIONS': {
                    'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                    'CONNECTION_POOL_KWARGS': {
                        'max_connections': 50,
                        'retry_on_timeout': True,
                        'socket_connect_timeout': 5,
                        'socket_timeout': 5,
                    },
                    'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
                    'IGNORE_EXCEPTIONS': True,  # Don't crash if Redis is down
                },
                'KEY_PREFIX': 'nexus_movies',
                'TIMEOUT': 300,  # 5 minutes default
                'VERSION': 1,
            }
        }
        
        # Use Redis for sessions only if Redis is working
        SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
        SESSION_CACHE_ALIAS = 'default'
        
        print("✅ Redis cache enabled and connected successfully")
        
    except Exception as e:
        # Redis not available, fallback to local memory cache
        print(f"⚠️ Redis not available ({str(e)}), falling back to local memory cache")
        USE_REDIS_CACHE = False
        
        CACHES = {
            'default': {
                'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
                'LOCATION': 'nexus-movie-cache',
                'TIMEOUT': 300,
                'OPTIONS': {
                    'MAX_ENTRIES': 1000,
                    'CULL_FREQUENCY': 3,
                }
            }
        }

if not USE_REDIS_CACHE:
    # Local memory cache fallback
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'nexus-movie-cache',
            'TIMEOUT': 300,
            'OPTIONS': {
                'MAX_ENTRIES': 1000,
                'CULL_FREQUENCY': 3,
            }
        }
    }
    print("📝 Using local memory cache")

# ==========================================
# TMDB API CONFIGURATION
# ==========================================
TMDB_API_KEY = config('TMDB_API_KEY', default='')
TMDB_BASE_URL = 'https://api.themoviedb.org/3'
TMDB_IMAGE_BASE_URL = 'https://image.tmdb.org/t/p/'

# ==========================================
# CACHE TTL CONFIGURATION
# ==========================================
CACHE_TTL = {
    'GENRES': 7 * 24 * 60 * 60,           # 7 days
    'MOVIE_DETAILS': 24 * 60 * 60,        # 24 hours
    'POPULAR_MOVIES': 60 * 60,            # 1 hour
    'TRENDING_MOVIES': 30 * 60,           # 30 minutes
    'SEARCH_RESULTS': 15 * 60,            # 15 minutes
    'RECOMMENDATIONS': 60 * 60,           # 1 hour
}

# ==========================================
# API DOCUMENTATION CONFIGURATION
# ==========================================
SPECTACULAR_SETTINGS = {
    'TITLE': 'Nexus Movie Recommendation API',
    'DESCRIPTION': (
        'A comprehensive movie recommendation system powered by TMDb API. '
        'Features user authentication, movie discovery, personalized recommendations, '
        'favorites, ratings, and watchlist management.'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': '/api/',
    'DEFAULT_GENERATOR_CLASS': 'drf_spectacular.generators.SchemaGenerator',
    
    # Authentication configuration for API docs
    'AUTHENTICATION_WHITELIST': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    
    # API documentation styling
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': False,
        'defaultModelsExpandDepth': 2,
        'defaultModelExpandDepth': 2,
        'displayRequestDuration': True,
        'filter': True,
    },
    
    # Additional API information
    'CONTACT': {
        'name': 'Nexus Development Team',
        'email': 'dev@nexus-movies.com',
    },
    'LICENSE': {
        'name': 'MIT License',
    },
    
    # Custom schema extensions
    'EXTENSIONS_INFO': {
        'x-api-id': 'nexus-movie-api',
    },
}

# ==========================================
# LOGGING CONFIGURATION
# ==========================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'nexus.log',
            'maxBytes': 1024*1024*10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'nexus_errors.log',
            'maxBytes': 1024*1024*5,  # 5 MB
            'backupCount': 3,
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'movies': {
            'handlers': ['file', 'console', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'accounts': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

# Override logging configuration for cloud deployment
if 'RENDER' in os.environ or not DEBUG:
    # Simplified logging for production - use console only
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'verbose': {
                'format': '{levelname} {asctime} {module} {message}',
                'style': '{',
            },
            'simple': {
                'format': '{levelname} {message}',
                'style': '{',
            },
        },
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
                'formatter': 'verbose',
            },
        },
        'root': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'loggers': {
            'django': {
                'handlers': ['console'],
                'level': 'INFO',
                'propagate': False,
            },
            'movies': {
                'handlers': ['console'],
                'level': 'INFO',
                'propagate': False,
            },
            'accounts': {
                'handlers': ['console'],
                'level': 'INFO',
                'propagate': False,
            },
        },
    }

# ==========================================
# SECURITY SETTINGS
# ==========================================
if not DEBUG:
    # Production security settings
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# ==========================================
# DEVELOPMENT SETTINGS
# ==========================================
if DEBUG:
    # Additional logging for development
    LOGGING['handlers']['debug'] = {
        'level': 'DEBUG',
        'class': 'logging.StreamHandler',
        'formatter': 'simple',
    }
    
    # Allow all CORS origins in development
    CORS_ALLOW_ALL_ORIGINS = True
    
    # Debug toolbar (optional - uncomment if you install it)
    # INSTALLED_APPS += ['debug_toolbar']
    # MIDDLEWARE += ['debug_toolbar.middleware.DebugToolbarMiddleware']
    # INTERNAL_IPS = ['127.0.0.1']

# Import for database URL parsing
import dj_database_url

# Production database configuration
if not DEBUG:
    # Use Railway's PostgreSQL database
    database_url = config('DATABASE_URL', default=None)
    if database_url:
        DATABASES = {
            'default': dj_database_url.parse(
                database_url,
                conn_max_age=600,
                conn_health_checks=True,
            )
        }

# Static files configuration for production
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Use whitenoise for static files in production
if 'whitenoise.middleware.WhiteNoiseMiddleware' not in MIDDLEWARE:
    # Add whitenoise after SecurityMiddleware
    middleware_list = list(MIDDLEWARE)
    security_index = middleware_list.index('django.middleware.security.SecurityMiddleware')
    middleware_list.insert(security_index + 1, 'whitenoise.middleware.WhiteNoiseMiddleware')
    MIDDLEWARE = middleware_list

# Static files storage
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Production security settings
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
    
    # Railway provides HTTPS
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Update ALLOWED_HOSTS for Railway
current_hosts = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')
ALLOWED_HOSTS = current_hosts + ['.railway.app', '.up.railway.app']

# Add this to detect Render environment in settings.py

# Render.com deployment detection
if 'RENDER' in os.environ:
    DEBUG = False
    ALLOWED_HOSTS = [
        os.environ.get('RENDER_EXTERNAL_HOSTNAME', ''),
        '.onrender.com',
        'localhost',
        '127.0.0.1'
    ]
    
    # Use PostgreSQL on Render
    if 'DATABASE_URL' in os.environ:
        import dj_database_url
        DATABASES = {
            'default': dj_database_url.parse(
                os.environ.get('DATABASE_URL'),
                conn_max_age=600,
                conn_health_checks=True,
            )
        }
    
    # Disable file-based logging on Render
    # (Already handled by LOGGING config above)

# ==========================================
# AUTO-CREATE SUPERUSER FOR RENDER
# ==========================================
if 'RENDER' in os.environ:
    import threading
    import time
    
    def create_render_superuser():
        """Create superuser for Render deployment"""
        time.sleep(5)  # Wait for Django to fully initialize
        
        try:
            from django.contrib.auth import get_user_model
            User = get_user_model()
            
            # Check if any superuser exists
            if not User.objects.filter(is_superuser=True).exists():
                # Create superuser with these specific credentials
                user = User.objects.create_superuser(
                    email='admin@nexusmovies.com',
                    password='NexusRender2024!',
                    first_name='Nexus',
                    last_name='Admin'
                )
                print("✅ RENDER SUPERUSER CREATED!")
                print("📧 Email: admin@nexusmovies.com") 
                print("🔐 Password: NexusRender2024!")
                print("🌐 Login at: https://movie-api-etrv.onrender.com/admin/")
                
            else:
                existing_user = User.objects.filter(is_superuser=True).first()
                print(f"ℹ️ Superuser already exists: {existing_user.email}")
                
        except Exception as e:
            print(f"⚠️ Error creating superuser: {e}")
    
    # Start the superuser creation in background
    thread = threading.Thread(target=create_render_superuser)
    thread.daemon = True
    thread.start()
