# Generated by Django 5.2.6 on 2025-09-27 06:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(help_text='TMDb Genre ID', unique=True)),
                ('name', models.CharField(help_text='Genre name', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(db_index=True, help_text='TMDb Movie ID', unique=True)),
                ('title', models.CharField(help_text='Movie title', max_length=255)),
                ('original_title', models.CharField(blank=True, help_text='Original title in native language', max_length=255)),
                ('overview', models.TextField(blank=True, help_text='Movie plot summary')),
                ('tagline', models.CharField(blank=True, help_text='Movie tagline', max_length=255)),
                ('release_date', models.DateField(blank=True, help_text='Movie release date', null=True)),
                ('runtime', models.PositiveIntegerField(blank=True, help_text='Runtime in minutes', null=True)),
                ('vote_average', models.FloatField(default=0.0, help_text='Average rating from TMDb (0-10)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('vote_count', models.PositiveIntegerField(default=0, help_text='Number of votes on TMDb')),
                ('popularity', models.FloatField(default=0.0, help_text='Popularity score from TMDb')),
                ('poster_path', models.CharField(blank=True, help_text='TMDb poster image path', max_length=255)),
                ('backdrop_path', models.CharField(blank=True, help_text='TMDb backdrop image path', max_length=255)),
                ('budget', models.BigIntegerField(blank=True, help_text='Movie budget in USD', null=True)),
                ('revenue', models.BigIntegerField(blank=True, help_text='Movie revenue in USD', null=True)),
                ('imdb_id', models.CharField(blank=True, help_text='IMDb ID', max_length=20)),
                ('original_language', models.CharField(default='en', help_text='Original language code', max_length=10)),
                ('production_countries', models.JSONField(blank=True, default=list, help_text='List of production countries')),
                ('spoken_languages', models.JSONField(blank=True, default=list, help_text='List of spoken languages')),
                ('status', models.CharField(default='Released', help_text='Movie status (Released, In Production, etc.)', max_length=20)),
                ('adult', models.BooleanField(default=False, help_text='Adult content flag')),
                ('last_updated_from_tmdb', models.DateTimeField(auto_now_add=True, help_text='Last sync with TMDb')),
                ('is_active', models.BooleanField(default=True, help_text='Movie is available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(blank=True, help_text='Movie genres', related_name='movies', to='movies.genre')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'ordering': ['-popularity', '-vote_average'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='movies.movie')),
            ],
            options={
                'verbose_name': 'Favorite',
                'verbose_name_plural': 'Favorites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '★☆☆☆☆ (1 star)'), (2, '★★☆☆☆ (2 stars)'), (3, '★★★☆☆ (3 stars)'), (4, '★★★★☆ (4 stars)'), (5, '★★★★★ (5 stars)')], help_text='Rating from 1-5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True, help_text='Optional written review', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_rating', models.FloatField(default=6.0, help_text='Minimum TMDb rating for recommendations', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('preferred_decade', models.CharField(blank=True, choices=[('2020s', '2020s'), ('2010s', '2010s'), ('2000s', '2000s'), ('1990s', '1990s'), ('1980s', '1980s'), ('classic', 'Classic (before 1980)')], help_text='Preferred movie decade', max_length=10)),
                ('include_adult', models.BooleanField(default=False, help_text='Include adult content')),
                ('preferred_languages', models.JSONField(blank=True, default=list, help_text='Preferred movie languages')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favorite_genres', models.ManyToManyField(blank=True, help_text="User's preferred genres", to='movies.genre')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='movie_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority')], default='medium', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Personal notes about this movie', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_watchlist', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Watchlist Item',
                'verbose_name_plural': 'Watchlist Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['tmdb_id'], name='movies_movi_tmdb_id_0e4cad_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['release_date'], name='movies_movi_release_b7ac7d_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['vote_average'], name='movies_movi_vote_av_ca6eee_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['popularity'], name='movies_movi_popular_114287_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'movie')},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'movie')},
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'movie')},
        ),
    ]
